import { ICandidate, EPosition } from 'models/interfaces/Candidate';

export const CANDIDATE: ICandidate[] = [
  {
    id: '1',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.President,
    party: '123',
    image: 'none',
    count: 12,
  },
  {
    id: '2',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.VicePresident,
    party: '123',
    image: 'none',
    count: 212,
  },
  {
    id: '3',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.Secretary,
    party: '123',
    image: 'none',
    count: 32,
  },
  {
    id: '4',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.Treasurer,
    party: '123',
    image: 'none',
    count: 62,
  },
  {
    id: '5',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.Auditor,
    party: '123',
    image: 'none',
    count: 132,
  },
  {
    id: '6',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.PeaceOfficer,
    party: '123',
    image: 'none',
    count: 312,
  },
  {
    id: '7',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.PublicInformationOfficer,
    party: '123',
    image: 'none',
    count: 432,
  },
  {
    id: '8',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeEightLevelRepresentative,
    party: '123',
    image: 'none',
    count: 412,
  },
  {
    id: '9',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeNineLevelRepresentative,
    party: '123',
    image: 'none',
    count: 422,
  },
  {
    id: '10',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeTenLevelRepresentative,
    party: '123',
    image: 'none',
    count: 122,
  },
  {
    id: '11',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeElevenLevelRepresentative,
    party: '123',
    image: 'none',
    count: 142,
  },
  {
    id: '12',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeTwelveLevelRepresentative,
    party: '123',
    image: 'none',
    count: 132,
  },
  {
    id: '21',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.President,
    party: '456',
    image: 'none',
    count: 112,
  },
  {
    id: '22',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.VicePresident,
    party: '456',
    image: 'none',
    count: 302,
  },
  {
    id: '23',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.Secretary,
    party: '456',
    image: 'none',
    count: 122,
  },
  {
    id: '24',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.Treasurer,
    party: '456',
    image: 'none',
    count: 121,
  },
  {
    id: '25',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.Auditor,
    party: '456',
    image: 'none',
    count: 12,
  },
  {
    id: '26',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.PeaceOfficer,
    party: '456',
    image: 'none',
    count: 120,
  },
  {
    id: '27',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.PublicInformationOfficer,
    party: '456',
    image: 'none',
    count: 12,
  },
  {
    id: '28',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeEightLevelRepresentative,
    party: '456',
    image: 'none',
    count: 102,
  },
  {
    id: '29',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeNineLevelRepresentative,
    party: '456',
    image: 'none',
    count: 112,
  },
  {
    id: '110',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeTenLevelRepresentative,
    party: '456',
    image: 'none',
    count: 252,
  },
  {
    id: '111',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeElevenLevelRepresentative,
    party: '456',
    image: 'none',
    count: 72,
  },
  {
    id: '112',
    firstName: 'Cedrick',
    lastName: 'Castro',
    position: EPosition.GradeTwelveLevelRepresentative,
    party: '456',
    image: 'none',
    count: 111,
  },
];
