// ANCHOR Interface
import { IRow } from '../../../interfaces/VoterDataTable';

export const VOTER_ROW: IRow[] = [
  {
    lrn: 123456789101,
    lastName: 'Castro',
    firstName: 'Prince Neil Cedrick',
    gradeLevel: 11,
    section: 'Faraday',
    status: true,
  },
  {
    lrn: 123456789201,
    lastName: 'Sanarez',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Galilei',
    status: false,
  },
  {
    lrn: 223456789201,
    lastName: 'Sanarez',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Galilei',
    status: false,
  },
  {
    lrn: 133456789201,
    lastName: 'Sanarez',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Galilei',
    status: true,
  },
  {
    lrn: 123446789201,
    lastName: 'Sanarez',
    firstName: 'Prince Cedrick',
    gradeLevel: 9,
    section: 'Dalton',
    status: true,
  },
  {
    lrn: 123416789201,
    lastName: 'Sanarez',
    firstName: 'Prince Cedrick',
    gradeLevel: 7,
    section: 'Padolina',
    status: false,
  },
  {
    lrn: 123156789201,
    lastName: 'Sanarez',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Galilei',
    status: true,
  },
  {
    lrn: 123456489201,
    lastName: 'Sanarez',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Newton',
    status: true,
  },
  {
    lrn: 123456489211,
    lastName: 'Castro',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Newton',
    status: true,
  },
  {
    lrn: 412381293192,
    lastName: 'Castro',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Newton',
    status: true,
  },
  {
    lrn: 410517381923,
    lastName: 'Castro',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Newton',
    status: true,
  },
  {
    lrn: 123453589211,
    lastName: 'Castro',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Newton',
    status: true,
  },
  {
    lrn: 123456481811,
    lastName: 'Castro',
    firstName: 'Prince Cedrick',
    gradeLevel: 10,
    section: 'Newton',
    status: true,
  },
].map((r) => ({ id: r.lrn, data: r }));
